//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeSCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditormaster
    {
        public string BatchNo { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string OldNRIC { get; set; }
        public string Nric { get; set; }
        public string CardNo { get; set; }
        public string AcNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string OffTel { get; set; }
        public string ResTel { get; set; }
        public string HpNo { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> AbortDate { get; set; }
        public Nullable<double> OSAmt { get; set; }
        public Nullable<double> MinPymt { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> LastPaidAmt { get; set; }
        public Nullable<System.DateTime> LastPaidDate { get; set; }
        public Nullable<double> HSLDOSAmt { get; set; }
        public string TPS1 { get; set; }
        public string TPS2 { get; set; }
        public string TPS3 { get; set; }
        public string OweTo { get; set; }
        public string Status { get; set; }
        public string TPSStatus { get; set; }
        public string Region { get; set; }
        public string Product { get; set; }
        public Nullable<double> TltAmtDue { get; set; }
        public Nullable<double> MinPayment1 { get; set; }
        public Nullable<double> MinPayment2 { get; set; }
        public string MIA { get; set; }
        public string GUARANTOR1 { get; set; }
        public string GUAddL1 { get; set; }
        public string GUAddL2 { get; set; }
        public string GUAddL3 { get; set; }
        public string GUOffTel { get; set; }
        public string GUResTel { get; set; }
        public string GUHP { get; set; }
        public string GUARANTOR2 { get; set; }
        public string GU2AddL1 { get; set; }
        public string GU2AddL2 { get; set; }
        public string GU2AddL3 { get; set; }
        public string GU2OffTel { get; set; }
        public string GU2ResTel { get; set; }
        public string GU2HP { get; set; }
        public string Others1 { get; set; }
        public string Others2 { get; set; }
        public Nullable<double> ADCH { get; set; }
        public Nullable<double> LateCharges { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> NoOfMonthArrears { get; set; }
        public Nullable<int> ContractLenght { get; set; }
        public Nullable<double> DELQ { get; set; }
        public Nullable<double> CashPrice { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public string LOCCD { get; set; }
    }
}
