//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeSCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customermaster
    {
        public string CustID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ColPymtPerc { get; set; }
        public Nullable<int> PymtPerc { get; set; }
        public string Status { get; set; }
    }
}
