//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DeSCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMaster
    {

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
        public string BatchNo { get; set; }
        public string AccNo { get; set; }
        public string OweTo { get; set; }
        public Nullable<double> PaidAmt { get; set; }

         [DataType(DataType.Currency)]
        public double Balance { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<double> Comm { get; set; }
        public Nullable<double> ColectorComm { get; set; }
        public string Verifiedby { get; set; }
        public string Status { get; set; }

        [DataType(DataType.Currency)]
        public Double ADCH { get; set; }

        
    }
}
