//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeSCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpsdetail
    {
        public int Id { get; set; }
        public string BatchNo { get; set; }
        public string AcNo { get; set; }
        public string OweTo { get; set; }
        public string Address { get; set; }
        public string ResTel { get; set; }
        public string OffTel { get; set; }
        public string HpNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string InfoBy { get; set; }
    }
}
