//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeSCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermaster
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public int UserLevel { get; set; }
        public string Position { get; set; }
        public string ReportingTo { get; set; }
        public string Department { get; set; }
    }
}
